; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_sfx_next
	.word @sfx_ntsc_sfx_back

@sfx_ntsc_sfx_next:
	.byte $81,$d5,$82,$00,$80,$3f,$89,$f0,$0a,$81,$bd,$0a,$81,$a9,$0a,$81
	.byte $9f,$0a,$81,$8e,$0a,$81,$7e,$0a,$81,$70,$8a,$0d,$89,$3f,$0a,$80
	.byte $30,$8a,$01,$14,$00
@sfx_ntsc_sfx_back:
	.byte $81,$70,$82,$00,$80,$3f,$89,$f0,$0a,$81,$7e,$0a,$81,$8e,$0a,$81
	.byte $9f,$0a,$81,$a9,$0a,$81,$bd,$0a,$81,$d5,$0a,$80,$30,$8a,$0d,$89
	.byte $3f,$0a,$8a,$01,$14,$00

.export sounds
